import type { Corpus } from "./schema";

/**
 * DrawMe prompt corpus — a stylistic equivalent of the classic KidPix DrawMe
 * "Chaos Randomizing" vocabulary. ORIGINAL TEXT, not verbatim KidPix content
 * (fan reproduction; see ../README.md for fidelity criteria). Vocabulary aims
 * at the same tone: short, silly, kid-friendly, fantastical, concrete enough
 * to draw. Sizes are intentionally similar to the original feel (~20 entries
 * per slot → tens of thousands of combinations).
 */
export const CORPUS: Corpus = {
  adjective: [
    "silly",
    "sleepy",
    "grumpy",
    "happy",
    "tiny",
    "giant",
    "polka-dotted",
    "striped",
    "fuzzy",
    "shiny",
    "invisible",
    "upside-down",
    "rainbow",
    "noisy",
    "sneaky",
    "magical",
    "rusty",
    "wobbly",
    "bouncy",
    "glow-in-the-dark",
  ],
  subject: [
    "dog",
    "cat",
    "robot",
    "dinosaur",
    "monkey",
    "pirate",
    "wizard",
    "octopus",
    "dragon",
    "frog",
    "alien",
    "snowman",
    "elephant",
    "submarine",
    "spaceship",
    "skateboard",
    "tuba",
    "cactus",
    "sandwich",
    "unicorn",
  ],
  action: [
    "dancing",
    "snoring",
    "juggling",
    "singing",
    "fishing",
    "skating",
    "flying",
    "hiding",
    "tickling a bee",
    "eating spaghetti",
    "riding a tricycle",
    "blowing bubbles",
    "painting a picture",
    "playing the drums",
    "building a fort",
    "stacking pancakes",
    "chasing a kite",
    "doing cartwheels",
    "telling a joke",
    "throwing a party",
  ],
  scene: [
    "on the moon",
    "under the sea",
    "in a jungle",
    "on a roller coaster",
    "inside a cereal box",
    "at the beach",
    "at the top of a mountain",
    "in outer space",
    "in a snowstorm",
    "in a haunted house",
    "in your backyard",
    "on a giant pizza",
    "in a cardboard rocket",
    "at the circus",
    "in an underwater cave",
    "on top of a castle",
    "in a thunderstorm",
    "on a flying carpet",
    "in a candy forest",
    "at the racetrack",
  ],
};
